python3 -c "
with open('modules/music/music.module.js') as f: c = f.read()
c = c.replace('export default async function initMusic(container) {', 'export default async function initMusic(container) {\n  var t = window.t || function(k,e){return e||k;};')
c = c.replace('content.innerHTML = \x60<div class=\"module-empty\"><i class=\"fa-solid fa-triangle-exclamation\"></i><p>Your browser blocks storage. Check Firefox settings', 'content.innerHTML = \x60<div class=\"module-empty\"><i class=\"fa-solid fa-triangle-exclamation\"></i><p>\x60 + t(\"d_musicStorageBlocked\", \"Your browser blocks storage. Check Firefox settings')
c = c.replace('make sure \"Never remember history\" is OFF.</p></div>\x60;', 'make sure \\u201cNever remember history\\u201d is OFF.\") + \x60</p></div>\x60;')
c = c.replace(\"'Failed to load music library.'\", 't(\"d_musicLoadFailed\", \"Failed to load music library.\")')
c = c.replace(\">' Retry\", '\"> \" + t(\"d_retry\", \"Retry\")')
c = c.replace(\"'No music loaded.'\", 't(\"d_musicNoMusic\", \"No music loaded.\")')
c = c.replace(\">' Add Music in Settings\", '\"> \" + t(\"d_musicAddSettings\", \"Add Music in Settings\")')
c = c.replace('stateSpan.innerText = \"Ready\";', 'stateSpan.innerText = t(\"d_musicReady\", \"Ready\");')
c = c.replace('stateSpan.innerText = \"Playing...\"', 'stateSpan.innerText = t(\"d_musicPlaying\", \"Playing...\")')
c = c.replace('stateSpan.innerText = \"Paused\"', 'stateSpan.innerText = t(\"d_paused\", \"Paused\")')
c = c.replace('stateSpan.innerText = \"Locked\"', 'stateSpan.innerText = t(\"d_musicLockedShort\", \"Locked\")')
c = c.replace('errorMsg = \"Cannot play file\"', 'errorMsg = t(\"d_musicCannotPlay\", \"Cannot play file\")')
c = c.replace('errorMsg = \"Playback aborted\"', 'errorMsg = t(\"d_musicAborted\", \"Playback aborted\")')
c = c.replace('errorMsg = \"Network error\"', 'errorMsg = t(\"d_musicNetwork\", \"Network error\")')
c = c.replace('errorMsg = \"File corrupted or unsupported format\"', 'errorMsg = t(\"d_musicCorrupted\", \"File corrupted or unsupported format\")')
c = c.replace('errorMsg = \"Format not supported\"', 'errorMsg = t(\"d_musicFormat\", \"Format not supported\")')
c = c.replace('errorMsg = \"Unknown error\"', 'errorMsg = t(\"d_musicUnknown\", \"Unknown error\")')
c = c.replace('showError(\"Cannot play file\")', 'showError(t(\"d_musicCannotPlay\", \"Cannot play file\"))')
c = c.replace('showError(\"Invalid file\")', 'showError(t(\"d_musicInvalid\", \"Invalid file\"))')
c = c.replace('showError(\"Cannot resume\")', 'showError(t(\"d_musicCannotResume\", \"Cannot resume\"))')
for i in range(5):
    c = c.replace('showError(\"Player locked', 'showError(t(\"d_musicLocked\", \"Player locked')
with open('modules/music/music.module.js','w') as f: f.write(c)
print('done')
"
